/* =============================================================================
   ELEMENT ASSEMBLY STUDIO PRO - EXTERIOR DOUBLE DOOR SYSTEM - UI CONFIGURATION
   =============================================================================

   FILE       : Na__AssemblyStudio__ExtDouble__UiSystem__Config__.js
   AUTHOR     : Noble Architecture
   PURPOSE    : Fielded-panel and opening UI controls for standalone exterior
                double doors. Defines shared leaf controls plus optional
                left/right override sections when leaf settings are unlinked.
   CREATED    : 2026

   DESCRIPTION:
   - Visible when ui_exterior_door_type === Double / double_door_mode.
   - Consumed by WindowSystem MainUiLogic via window.NA_EXT_DOUBLE_DOOR_CONFIG
     (legacy alias: window.NA_DOUBLE_DOOR_CONFIG).
   - Per-leaf override controls are generated by na_leaf_override_controls
     for left and right sides under double_door_{side}_* keys.

   ============================================================================= */


// =============================================================================
// REGION | ExtDouble UI Config Module
// =============================================================================

const Na__ExtDouble__UiConfig = (function () {

    'use strict';


    // -----------------------------------------------------------------------------
    // REGION | Control Descriptor Helpers
    // -----------------------------------------------------------------------------

    // HELPER FUNCTION | Build a Select Control Descriptor
    // ------------------------------------------------------------
    function na_select(id, label, defaultValue, options, section) {
        return {
            id: id, label: label, type: 'select',
            default: defaultValue, options: options, section: section
        };
    }
    // ---------------------------------------------------------------

    // HELPER FUNCTION | Build a Millimetre Slider Control Descriptor
    // ------------------------------------------------------------
    function na_slider(id, label, minimum, maximum, step, defaultValue, section) {
        return {
            id: id, label: label, type: 'slider',
            min: minimum, max: maximum, step: step,
            default: defaultValue, unit: 'mm', section: section
        };
    }
    // ---------------------------------------------------------------

    // HELPER FUNCTION | Build a Toggle Control Descriptor
    // ------------------------------------------------------------
    function na_checkbox(id, label, defaultValue, section) {
        return {
            id: id, label: label, type: 'toggle',
            default: defaultValue, section: section
        };
    }
    // ---------------------------------------------------------------

    // endregion -------------------------------------------------------------------


    // -----------------------------------------------------------------------------
    // REGION | Shared Option Lists
    // -----------------------------------------------------------------------------

    const NA_COMPOSITIONS = [
        { value: 'FullyGlazed', label: 'Fully Glazed' },
        { value: 'GlazedOverFielded', label: 'Glazed Over Fielded' },
        { value: 'FullyFielded', label: 'Fully Fielded' }
    ];

    const NA_PRESETS = [
        { value: 'OnePanel', label: 'One Panel' },
        { value: 'TwoVertical', label: 'Two Vertical' },
        { value: 'TwoHorizontal', label: 'Two Horizontal' },
        { value: 'FourPanel', label: 'Four Panel' },
        { value: 'SixPanel', label: 'Six Panel' },
        { value: 'Custom', label: 'Custom' }
    ];

    // endregion -------------------------------------------------------------------


    // -----------------------------------------------------------------------------
    // REGION | Shared Leaf Controls
    // -----------------------------------------------------------------------------

    const NA_SHARED_CONTROLS = [
        // Fixed Panels turns the pair into dead joinery - no handles, no ROT
        // hinge markers, no open-state copy, no swing arcs. Built for orangery
        // and conservatory runs where only the centre pair actually opens but
        // every panel must share the same stile / rail / glazing bar language.
        na_checkbox('double_door_fixed_panels', 'Fixed Panels', false, 'Opening and Leaves'),
        Object.assign(na_select('double_door_active_leaf', 'Active Leaf', 'Left', [
            { value: 'Left', label: 'Left Leaf' },
            { value: 'Right', label: 'Right Leaf' }
        ], 'Opening and Leaves'), { type: 'binary_toggle' }),
        {
            id: 'double_door_active_leaf_width_mm',
            label: 'Active Leaf Width',
            type: 'eq_number',
            default: 'EQ',
            section: 'Opening and Leaves'
        },
        Object.assign(na_select('double_door_swing_direction', 'Swing Direction', 'Inward', [
            { value: 'Inward', label: 'Inward' },
            { value: 'Outward', label: 'Outward' }
        ], 'Opening and Leaves'), { type: 'binary_toggle' }),
        Object.assign(
            na_slider('double_door_left_opening_angle_deg', 'Left Opening Angle', 0, 180, 5, 90, 'Opening and Leaves'),
            { unit: '°' }
        ),
        Object.assign(
            na_slider('double_door_right_opening_angle_deg', 'Right Opening Angle', 0, 180, 5, 90, 'Opening and Leaves'),
            { unit: '°' }
        ),
        na_slider('double_door_left_hinge_projection_mm', 'Left Hinge Projection', 0, 150, 5, 0, 'Opening and Leaves'),
        na_slider('double_door_right_hinge_projection_mm', 'Right Hinge Projection', 0, 150, 5, 0, 'Opening and Leaves'),

        na_checkbox('double_door_show_swing_arcs', 'Show 2D Swing Arcs', true, 'Swing Output'),
        na_checkbox('double_door_create_open_state_copy', 'Create Open-State Copy', true, 'Swing Output'),

        na_checkbox('double_door_leaf_settings_linked', 'Link Leaf Settings', true, 'Leaf Construction'),
        na_select('double_door_leaf_composition', 'Leaf Composition', 'GlazedOverFielded', NA_COMPOSITIONS, 'Leaf Construction'),
        na_slider('double_door_leaf_thickness_mm', 'Leaf Thickness', 30, 80, 1, 50, 'Leaf Construction'),
        na_slider('double_door_panel_stile_width_mm', 'Perimeter Stile Width', 40, 250, 5, 95, 'Leaf Construction'),
        na_slider('double_door_panel_top_rail_width_mm', 'Top Rail Width', 40, 300, 5, 95, 'Leaf Construction'),
        na_slider('double_door_panel_bottom_rail_width_mm', 'Bottom Rail Width', 40, 400, 5, 150, 'Leaf Construction'),
        na_slider('double_door_mid_rail_width_mm', 'Separating Midrail Width', 40, 300, 5, 120, 'Leaf Construction'),

        na_select('double_door_panel_output_mode', 'Panel Output', 'ThreeDimensional', [
            { value: 'Linework', label: 'Linework' },
            { value: 'ThreeDimensional', label: 'Three Dimensional' }
        ], 'Fielded Panels'),
        na_select('double_door_panel_profile', 'Panel Profile', 'RaisedBevelled', [
            { value: 'RaisedBevelled', label: 'Raised Bevelled' },
            { value: 'RecessedShaker', label: 'Recessed Shaker' }
        ], 'Fielded Panels'),
        na_select('double_door_panel_preset', 'Panel Layout', 'OnePanel', NA_PRESETS, 'Fielded Panels'),
        Object.assign(na_slider('double_door_panel_columns', 'Custom Columns', 1, 6, 1, 1, 'Fielded Panels'), { unit: '' }),
        Object.assign(na_slider('double_door_panel_rows', 'Custom Rows', 1, 6, 1, 1, 'Fielded Panels'), { unit: '' }),
        na_slider('double_door_fielded_section_height_mm', 'Fielded Section Height', 100, 1800, 5, 300, 'Fielded Panels'),
        na_slider('double_door_panel_inset_mm', 'Panel Inset', 5, 100, 1, 25, 'Fielded Panels'),
        na_slider('double_door_panel_depth_mm', 'Panel Depth', 1, 30, 1, 12, 'Fielded Panels'),
        na_slider('double_door_panel_bevel_width_mm', 'Panel Bevel Width', 2, 60, 1, 18, 'Fielded Panels'),

        Object.assign(na_select('double_door_handle_pairing', 'Handles', 'Paired', [
            { value: 'Single', label: 'Single' },
            { value: 'Paired', label: 'Paired' }
        ], 'Hardware'), { type: 'binary_toggle' }),
        na_select('double_door_handle_asset_key', 'Handle Asset', 'Na__ExteriorDoor__Handle__Scroll', [], 'Hardware'),
        na_slider('double_door_handle_height_mm', 'Handle Height', 700, 1400, 5, 900, 'Hardware'),
        na_slider('double_door_handle_backset_mm', 'Handle Position from Meeting Stile', 20, 250, 5, 40, 'Hardware'),
        {
            id: 'double_door_leaf_material_id',
            label: 'Leaf Finish',
            type: 'material_cards',
            default: 'MAT120__GenericWood',
            materialsSource: 'NA_FRAME_FINISH_SWATCHES',
            section: 'Finishes'
        },
        {
            id: 'double_door_handle_material_id',
            label: 'Handle Finish',
            type: 'material_cards',
            default: 'MAT615__Metal__Ironmongery__Chrome',
            materialsSource: 'NA_HANDLE_FINISH_SWATCHES',
            section: 'Finishes'
        }
    ];

    // endregion -------------------------------------------------------------------


    // -----------------------------------------------------------------------------
    // REGION | Per-Leaf Override Controls
    // -----------------------------------------------------------------------------

    // FUNCTION | Build Override Control Set for One Leaf Side
    // ------------------------------------------------------------
    function na_leaf_override_controls(side, label) {
        const prefix  = 'double_door_' + side + '_';
        const section = label + ' Override';
        return [
            na_checkbox(prefix + 'leaf_override_enabled', 'Enable ' + label + ' Override', false, section),
            na_select(prefix + 'leaf_composition', 'Composition', 'GlazedOverFielded', NA_COMPOSITIONS, section),
            na_select(prefix + 'panel_output_mode', 'Panel Output', 'ThreeDimensional', [
                { value: 'Linework', label: 'Linework' },
                { value: 'ThreeDimensional', label: 'Three Dimensional' }
            ], section),
            na_select(prefix + 'panel_profile', 'Panel Profile', 'RaisedBevelled', [
                { value: 'RaisedBevelled', label: 'Raised Bevelled' },
                { value: 'RecessedShaker', label: 'Recessed Shaker' }
            ], section),
            na_select(prefix + 'panel_preset', 'Panel Layout', 'OnePanel', NA_PRESETS, section),
            Object.assign(na_slider(prefix + 'panel_columns', 'Custom Columns', 1, 6, 1, 1, section), { unit: '' }),
            Object.assign(na_slider(prefix + 'panel_rows', 'Custom Rows', 1, 6, 1, 1, section), { unit: '' }),
            na_slider(prefix + 'fielded_section_height_mm', 'Fielded Section Height', 100, 1800, 5, 300, section),
            na_slider(prefix + 'mid_rail_width_mm', 'Separating Midrail Width', 40, 300, 5, 120, section),
            na_slider(prefix + 'panel_stile_width_mm', 'Perimeter Stile Width', 40, 250, 5, 95, section),
            na_slider(prefix + 'panel_top_rail_width_mm', 'Top Rail Width', 40, 300, 5, 95, section),
            na_slider(prefix + 'panel_bottom_rail_width_mm', 'Bottom Rail Width', 40, 400, 5, 150, section),
            na_slider(prefix + 'panel_inset_mm', 'Panel Inset', 5, 100, 1, 25, section),
            na_slider(prefix + 'panel_depth_mm', 'Panel Depth', 1, 30, 1, 12, section),
            na_slider(prefix + 'panel_bevel_width_mm', 'Panel Bevel Width', 2, 60, 1, 18, section),
            Object.assign(na_slider(prefix + 'horizontal_glaze_bars', 'Horizontal Glaze Bars', 0, 12, 1, 0, section), { unit: '' }),
            Object.assign(na_slider(prefix + 'vertical_glaze_bars', 'Vertical Glaze Bars', 0, 12, 1, 0, section), { unit: '' }),
            na_slider(prefix + 'glaze_bar_width_mm', 'Glaze Bar Width', 5, 100, 1, 25, section),
            na_slider(prefix + 'glazebar_inset_mm', 'Glaze Bar Inset', 0, 100, 1, 10, section)
        ];
    }
    // ---------------------------------------------------------------

    // endregion -------------------------------------------------------------------


    // -----------------------------------------------------------------------------
    // REGION | Assembled Control List
    // -----------------------------------------------------------------------------

    const NA_CONTROLS = NA_SHARED_CONTROLS
        .concat(na_leaf_override_controls('left', 'Left Leaf'))
        .concat(na_leaf_override_controls('right', 'Right Leaf'));

    // endregion -------------------------------------------------------------------


    return {
        na_controls     : NA_CONTROLS,
        na_compositions : NA_COMPOSITIONS,
        na_presets      : NA_PRESETS
    };

})();


// =============================================================================
// REGION | Browser Global Attachment
// =============================================================================

window.Na__ExtDouble__UiConfig      = Object.freeze(Na__ExtDouble__UiConfig);
window.NA_EXT_DOUBLE_DOOR_CONFIG    = Na__ExtDouble__UiConfig.na_controls;
window.NA_DOUBLE_DOOR_CONFIG        = Na__ExtDouble__UiConfig.na_controls;                 // <-- Legacy alias

// endregion -------------------------------------------------------------------


/* =============================================================================
   END OF FILE
   ============================================================================= */
