# =============================================================================
# NA NOBLE3D MODELLING TOOLS - LATTICE MAKER - SOLID OPS HELPERS
# =============================================================================
#
# FILE       : Na__Noble3dModellingTools__LatticeMaker__SolidOps__.rb
# NAMESPACE  : Na__Noble3dModellingTools::Na__LatticeMaker__SolidOps
# PURPOSE    : Solid cleanup, culling, and topology repair helpers
# CREATED    : 2026
#
# =============================================================================

module Na__Noble3dModellingTools
    module Na__LatticeMaker__SolidOps

# -----------------------------------------------------------------------------
# REGION | Face and Intersection Operations
# -----------------------------------------------------------------------------

        # FUNCTION | Force Self Intersection on Group Entities
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__ForceGroupSelfIntersection(group)
            return [] unless group && group.valid?

            entities = group.entities
            identity = Geom::Transformation.new
            source_entities = entities.to_a.select { |entity| entity.valid? }
            return [] if source_entities.empty?

            entities.intersect_with(
                false,
                identity,
                entities,
                identity,
                false,
                source_entities
            )
        rescue
            []
        end
        # ------------------------------------------------------------

        # FUNCTION | Return Planar Faces Parallel to Target Normal
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__FindPlanarSurfaceFaces(entities, normal)
            entities.grep(Sketchup::Face).select do |face|
                face.valid? && self.Na__LatticeMaker__FaceParallelToNormal(face, normal)
            end
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True When Face is Parallel to Normal
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__FaceParallelToNormal(face, normal)
            return false unless face.valid?

            face_normal = face.normal
            return false if face_normal.length == 0.0

            face_normal.dot(normal).abs > 0.9999
        end
        # ------------------------------------------------------------

        # FUNCTION | Orient Faces to Match Target Normal
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__OrientFacesToNormal(faces, normal)
            faces.each do |face|
                next unless face.valid?

                face.reverse! if face.normal.dot(normal) < 0.0
            end
        end
        # ------------------------------------------------------------

        # FUNCTION | PushPull Surface Faces Along Normal Direction
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PushPullSurfaceFaces(faces, depth, normal)
            faces.each do |face|
                next unless face.valid?

                face.reverse! if face.normal.dot(normal) < 0.0
                face.pushpull(depth, false)
            end
        end
        # ------------------------------------------------------------

# endregion -------------------------------------------------------------------

# -----------------------------------------------------------------------------
# REGION | Internal Face Culling
# -----------------------------------------------------------------------------

        # FUNCTION | Remove Internal Faces Generated by Lattice Solid
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__RemoveInternalFacesFromGeneratedSolid(entities, working_plane, solid_prisms, depth)
            removed_total = 0

            3.times do
                internal_faces = self.Na__LatticeMaker__FindInternalFacesFromGeneratedSolid(
                    entities,
                    working_plane,
                    solid_prisms,
                    depth
                )
                break if internal_faces.empty?

                entities.erase_entities(internal_faces)
                removed_total += internal_faces.length
                self.Na__LatticeMaker__CleanLooseEdgesOnly(entities)
            end

            removed_total
        end
        # ------------------------------------------------------------

        # FUNCTION | Return Internal Faces from Generated Solid
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__FindInternalFacesFromGeneratedSolid(entities, working_plane, solid_prisms, depth)
            sample_offset = self.Na__LatticeMaker__InternalFaceSampleOffset(depth)
            tolerance = self.Na__LatticeMaker__InternalFaceTolerance(depth)

            entities.grep(Sketchup::Face).select do |face|
                next false unless face.valid?

                face_center = self.Na__LatticeMaker__FaceCentroid(face)
                face_normal = face.normal.clone
                next false if face_normal.length < 0.001

                face_normal.normalize!

                offset_vector = face_normal.clone
                offset_vector.length = sample_offset

                front_sample_world = face_center + offset_vector
                back_sample_world = face_center - offset_vector

                front_sample_local = front_sample_world.transform(working_plane[:to_local])
                back_sample_local = back_sample_world.transform(working_plane[:to_local])

                front_inside = self.Na__LatticeMaker__PointInsideGeneratedSolidPrisms(front_sample_local, solid_prisms, tolerance)
                back_inside = self.Na__LatticeMaker__PointInsideGeneratedSolidPrisms(back_sample_local, solid_prisms, tolerance)

                front_inside && back_inside
            end
        end
        # ------------------------------------------------------------

        # FUNCTION | Return Sample Offset Used for Internal Face Test
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__InternalFaceSampleOffset(depth)
            ideal = depth.abs * 0.10
            lower_limit = 0.05.mm
            upper_limit = [depth.abs * 0.25, 0.5.mm].min
            [[ideal, lower_limit].max, upper_limit].min
        end
        # ------------------------------------------------------------

        # FUNCTION | Return Tolerance Used for Internal Face Test
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__InternalFaceTolerance(depth)
            [[depth.abs * 0.025, 0.05.mm].max, 0.25.mm].min
        end
        # ------------------------------------------------------------

        # FUNCTION | Return Face Centroid Point
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__FaceCentroid(face)
            vertices = face.vertices
            count = vertices.length.to_f

            sum_x = 0.0
            sum_y = 0.0
            sum_z = 0.0

            vertices.each do |vertex|
                point = vertex.position
                sum_x += point.x
                sum_y += point.y
                sum_z += point.z
            end

            Geom::Point3d.new(sum_x / count, sum_y / count, sum_z / count)
        end
        # ------------------------------------------------------------

# endregion -------------------------------------------------------------------

# -----------------------------------------------------------------------------
# REGION | Point-In-Solid Tests
# -----------------------------------------------------------------------------

        # FUNCTION | Return True if Point is in Any Prism
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PointInsideGeneratedSolidPrisms(local_point, solid_prisms, tolerance)
            solid_prisms.any? do |prism|
                self.Na__LatticeMaker__PointInsideGeneratedSolidPrism(local_point, prism, tolerance)
            end
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True if Point is in Single Prism
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PointInsideGeneratedSolidPrism(local_point, prism, tolerance)
            return false if local_point.z < (prism[:min_z] - tolerance)
            return false if local_point.z > (prism[:max_z] + tolerance)

            self.Na__LatticeMaker__PointInsidePolygon2d(local_point, prism[:polygon], tolerance)
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True if Point is Inside Polygon
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PointInsidePolygon2d(local_point, polygon, tolerance)
            return true if self.Na__LatticeMaker__PointOnPolygonBoundary2d(local_point, polygon, tolerance)

            inside = false
            point_x = local_point.x
            point_y = local_point.y
            j = polygon.length - 1

            polygon.each_with_index do |vertex_i, i|
                vertex_j = polygon[j]
                xi = vertex_i.x
                yi = vertex_i.y
                xj = vertex_j.x
                yj = vertex_j.y

                crosses_y = (yi > point_y) != (yj > point_y)
                if crosses_y
                    denominator = yj - yi
                    if denominator.abs > 0.000001
                        x_at_y = xi + ((point_y - yi) * (xj - xi) / denominator)
                        inside = !inside if point_x < x_at_y
                    end
                end

                j = i
            end

            inside
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True if Point is On Polygon Edge Boundary
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PointOnPolygonBoundary2d(local_point, polygon, tolerance)
            polygon.each_with_index do |start_point, index|
                end_point = polygon[(index + 1) % polygon.length]
                return true if self.Na__LatticeMaker__PointNearSegment2d(local_point, start_point, end_point, tolerance)
            end

            false
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True if Point is Near Segment Within Tolerance
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__PointNearSegment2d(point, segment_start, segment_end, tolerance)
            px = point.x
            py = point.y
            ax = segment_start.x
            ay = segment_start.y
            bx = segment_end.x
            by = segment_end.y

            abx = bx - ax
            aby = by - ay
            apx = px - ax
            apy = py - ay

            ab_length_squared = (abx * abx) + (aby * aby)
            return Math.sqrt((apx * apx) + (apy * apy)) <= tolerance if ab_length_squared <= 0.000001

            t = ((apx * abx) + (apy * aby)) / ab_length_squared
            t = [[t, 0.0].max, 1.0].min

            closest_x = ax + (abx * t)
            closest_y = ay + (aby * t)
            dx = px - closest_x
            dy = py - closest_y

            Math.sqrt((dx * dx) + (dy * dy)) <= tolerance
        end
        # ------------------------------------------------------------

# endregion -------------------------------------------------------------------

# -----------------------------------------------------------------------------
# REGION | Edge Cleanup Helpers
# -----------------------------------------------------------------------------

        # FUNCTION | Remove Loose and Coplanar Divider Edges
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__CleanStragglerEdges(entities)
            removed_total = 0

            10.times do
                edges_to_erase = entities.grep(Sketchup::Edge).select do |edge|
                    next false unless edge.valid?

                    self.Na__LatticeMaker__LooseEdge(edge) || self.Na__LatticeMaker__CoplanarDividerEdge(edge)
                end
                break if edges_to_erase.empty?

                entities.erase_entities(edges_to_erase)
                removed_total += edges_to_erase.length
            end

            removed_total
        end
        # ------------------------------------------------------------

        # FUNCTION | Remove Only Loose Edges
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__CleanLooseEdgesOnly(entities)
            loose_edges = entities.grep(Sketchup::Edge).select do |edge|
                edge.valid? && self.Na__LatticeMaker__LooseEdge(edge)
            end

            entities.erase_entities(loose_edges) unless loose_edges.empty?
            loose_edges.length
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True When Edge Has No Faces
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__LooseEdge(edge)
            edge.faces.empty?
        end
        # ------------------------------------------------------------

        # FUNCTION | Return True When Edge Splits Coplanar Faces
        # ------------------------------------------------------------
        def self.Na__LatticeMaker__CoplanarDividerEdge(edge)
            return false unless edge.faces.length == 2

            face_a = edge.faces[0]
            face_b = edge.faces[1]
            return false unless face_a.valid? && face_b.valid?

            face_a.coplanar_with?(face_b)
        rescue
            false
        end
        # ------------------------------------------------------------

# endregion -------------------------------------------------------------------

    end # module Na__LatticeMaker__SolidOps
end # module Na__Noble3dModellingTools

# =============================================================================
# END OF FILE
# =============================================================================
